spring:
  profiles: lzt
  datasource:
    url: jdbc:postgresql://10.10.11.24:9999/lzt-test
    username: ota
    password: ota@fanqie.COM888
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class: org.postgresql.Driver
    max-active: 10
    min-idle: 1
    max-wait: 60000
    remove-abandoned: true
    test-on-borrow: true
    remove-abandoned-timeout: 120
    log-abandoned: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true

---
spring:
  profiles: departure
  datasource:
    url: jdbc:postgresql://10.10.11.24:9999/departure
    username: ota
    password: ota@fanqie.COM888
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class: org.postgresql.Driver
    max-active: 10
    min-idle: 1
    max-wait: 60000
    remove-abandoned: true
    test-on-borrow: true
    remove-abandoned-timeout: 120
    log-abandoned: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
  jpa:
    show-sql: true

---
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index,/login/**,/favicon.ico,/admin/*